export enum links {
    login = 'login',
    verification = 'Verification',
    singUp = 'SingUp',
    MainScreen = 'MainScreen',
    home = 'Home',
    unloading = 'Unloading',
    loadingVerified1 = 'LoadVerified1',
    loadingVerified2 = 'LoadVerified2',
    loadingVerified3 = 'LoadVerified3',
    loadingVerified4 = 'LoadVerified4',
    bids = 'Bids',
    loadInfo = 'LoadInfo',
    bidDetail = 'BidDetail',
    bidDetailForActiveLoads = 'BidDetailForActiveLoads',
    filter = 'Filter',
    chat = 'Chat',
    callScreen = 'CallScreen',
    chatContent = 'ChatContent',
    profile = 'Profile',
    editProfile = 'EditProfile',
    completedLoads = 'CompletedLoads',
    notAvailable = 'NotAvailable',
    camera = 'Camera',
    myCards = 'MyCards',
    editCardData = 'EditCardData'
}
